import fs from "fs";
import crypto from "crypto";
import path from "path";

const approvedSegments = {
  "AB": { name: "Air Blender", internalSubgroup: "Access Segments" },
  "AF": { name: "Angle Filter", internalSubgroup: "Filter Segments" },
  "AT": { name: "Sound Attenuator", internalSubgroup: "Access Segments" },
  "CC": { name: "Coil (Cooling)", internalSubgroup: "Coil Segments" },
  "DI": { name: "Diffuser", internalSubgroup: "Access Segments" },
  "DP": { name: "Discharge Plenum", internalSubgroup: "Access Segments" },
  "EB": { name: "External Bypass", internalSubgroup: "Access Segments" },
  "EE": { name: "Economizer", internalSubgroup: "Access Segments" },
  "EF": { name: "Filter Economizer", internalSubgroup: "Filter Segments" },
  "EH": { name: "Electric Heat", internalSubgroup: "Coil Segments" },
  "FD": { name: "Face Damper", internalSubgroup: "Access Segments" },
  "FE": { name: "Fan (Exhaust)", internalSubgroup: "Fan Segments" },
  "FF": { name: "Flat Filter", internalSubgroup: "Filter Segments" },
  "FM": { name: "Filter Mixing Box", internalSubgroup: "Filter Segments" },
  "FR": { name: "Fan (Return)", internalSubgroup: "Fan Segments" },
  "FS": { name: "Fan (Supply)", internalSubgroup: "Fan Segments" },
  "HC": { name: "Coil (Heating)", internalSubgroup: "Coil Segments" },
  "HD": { name: "Hot Deck", internalSubgroup: "Coil Segments" },
  "HF": { name: "HEPA Filter", internalSubgroup: "Filter Segments" },
  "HM": { name: "Humidifier", internalSubgroup: "Access Segments" },
  "HW": { name: "Heat Wheel", internalSubgroup: "Access Segments" },
  "HX": { name: "Heat Exchanger", internalSubgroup: "Access Segments" },
  "IB": { name: "Internal Bypass", internalSubgroup: "Access Segments" },
  "IC": { name: "Integrated Face and Bypass Coil", internalSubgroup: "Coil Segments" },
  "IG": { name: "Indirect Fired Gas", internalSubgroup: "Coil Segments" },
  "IO": { name: "Inlet / Outlet", internalSubgroup: "Access Segments" },
  "IP": { name: "Inlet Plenum", internalSubgroup: "Access Segments" },
  "MB": { name: "Mixing Box", internalSubgroup: "Access Segments" },
  "PC": { name: "Pipe Chase", internalSubgroup: "Access Segments" },
  "RF": { name: "High Efficiency Filter", internalSubgroup: "Filter Segments" },
  "TN": { name: "Turning", internalSubgroup: "Access Segments" },
  "UV": { name: "UV Light", internalSubgroup: "Access Segments" },
  "VC": { name: "Vertical Coil", internalSubgroup: "Coil Segments" },
  "VE": { name: "Vertical Economizer", internalSubgroup: "Access Segments" },
  "VB": { name: "Vestibule / Corridor", internalSubgroup: "Access Segments" },
  "VP": { name: "Vertical Plenum", internalSubgroup: "Access Segments" },
  "XA": { name: "Access", internalSubgroup: "Access Segments" }
};

const approvedInternals = [
  "Access Panel",
  "Air Blender",
  "Angle Filter",
  "Coil (Cooling)",
  "Coil (DX)",
  "Coil (Heating)",
  "Coil (Split)",
  "Coil (SQ)",
  "Coil (Staggered)",
  "Coil (Wing/IC)",
  "Coil Panel",
  "Damper Wall",
  "Drain Pan",
  "Drain Pan (Aux)",
  "EBM Fan Wall",
  "Electric Heater",
  "Filter (HEPA)",
  "Flat Filter",
  "Heat Exchanger",
  "Heat Wheel",
  "Humidifier",
  "Indirect Gas Heater",
  "Perf Basket(s)",
  "Rigid Filter",
  "Sound Attenuator",
  "UV Light Wall"
];

const approvedMappings = {
  version: "14.0.0",
  approvedSegments,
  approvedInternals,
  approvedVendorCodes: {
    "DDPG2": { name: "Direct Drive Plenum Fan Gen 2", category: "Fans", isApproved: true, requiresConfirmation: false },
    "EBM_EC": { name: "EBM Electronically Commutated Fan", category: "Fans", isApproved: true, requiresConfirmation: false },
    "TCF_CL3": { name: "Twin City Fan Class 3", category: "Fans", isApproved: true, requiresConfirmation: false }
  },
  materialCompatibility: {
    "ALUMINUM_LINER_RECONNECT": "SST304",
    "ALUMINUM_DRAIN_HOLE_DIA": 3.125,
    "STEEL_DRAIN_HOLE_DIA": 1.50,
    "RIVET_PERIMETER_HOLE_DIA": 0.25,
    "WELD_PERIMETER_HOLE_DIA": 0.50,
    "ALUMINUM_CORNER_LINER_GAUGE": 14
  }
};

const rules = [
  // =========================================================================
  // 1. BASE (Scope: Skid, No Subgroups)
  // =========================================================================
  {
    id: "BASE-01",
    semanticKey: "BASE_LIFTING_LUG_SUPPORT",
    scope: "Skid",
    category: "Base",
    order: 1,
    text: "Lifting lugs Have proper support when the skid is over 4,000lbs (Ref ASSY Manual page 391-40206-003)",
    reference: "ASSY Manual p.391-40206-003",
    excelRow: 29,
    requiredFacts: ["skid.weight"],
    predicate: { ">": [{ var: "skid.weight" }, 4000] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-02",
    semanticKey: "BASE_LIFTING_LUG_CLEARANCE",
    scope: "Skid",
    category: "Base",
    order: 2,
    text: "Lifting lugs are free of obstruction/interference around drains, coil connections, VFDs, etc. (Standard 6\" minimum).",
    reference: "Std Assembly Spec Sec 4.2",
    excelRow: 30,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-03",
    semanticKey: "BASE_FLOOR_DRAINS_PRESENT",
    scope: "Skid",
    category: "Base",
    order: 3,
    text: "Floor drains are present and located as shown on the Unit Editor.",
    reference: "Unit Editor Layout Plan",
    excelRow: 31,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-04",
    semanticKey: "BASE_FLOOR_DRAIN_HOLE_SIZE",
    scope: "Skid",
    category: "Base",
    order: 4,
    text: "Floor drain hole sizes are correct: 3.125\" dia for AL Drains; 1.50\" dia for Steel Drains.",
    reference: "Base Fab Dwg 391-10001-002",
    excelRow: 32,
    requiredFacts: ["unit.floorMaterial"],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-05",
    semanticKey: "BASE_SKIN_SEAMS_SUPPORT",
    scope: "Skid",
    category: "Base",
    order: 5,
    text: "Skin Seams have proper base steel support.",
    reference: "Base Structural Guideline",
    excelRow: 40,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-06",
    semanticKey: "BASE_FLOOR_SKIN_MAX_SIZE",
    scope: "Skid",
    category: "Base",
    order: 6,
    text: "Material size does NOT exceed 144\" x 48\"; 60\" x 144\" for Aluminum Diamond Plate floor skin.",
    reference: "Sheet Metal Sizing Std",
    excelRow: 41,
    requiredFacts: ["unit.floorMaterial"],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-07",
    semanticKey: "BASE_FLOOR_SKIN_GAUGE",
    scope: "Skid",
    category: "Base",
    order: 7,
    text: "Floor skins have correct material type and gauge.",
    reference: "Unit Schedule Specs",
    excelRow: 42,
    requiredFacts: ["unit.floorMaterial", "unit.floorGauge"],
    allowNA: false,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-08",
    semanticKey: "BASE_NON_FULL_DRAIN_SUPPORT",
    scope: "Skid",
    category: "Base",
    order: 8,
    text: "Floor skins around non-full width drainpans have proper skin seam support.",
    reference: "Drain Pan Casing Std",
    excelRow: 43,
    requiredFacts: ["skid.hasDrainPan"],
    predicate: { "===": [{ var: "skid.hasDrainPan" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-09",
    semanticKey: "BASE_SUBFLOOR_PULLBACK",
    scope: "Skid",
    category: "Base",
    order: 9,
    text: "Subfloors are pulled back 0.25\" from full height formed channels like they are from structural channels.",
    reference: "Subfloor Assembly Detail",
    excelRow: 45,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-10",
    semanticKey: "BASE_COMPONENT_SUPPORT",
    scope: "Skid",
    category: "Base",
    order: 10,
    text: "Component Support - There is proper support under components that require base steel supports.",
    reference: "Heavy Component Load Spec",
    excelRow: 47,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-11",
    semanticKey: "BASE_FORMED_CHANNELS_CURB_REST",
    scope: "Skid",
    category: "Base",
    order: 11,
    text: "Full height Formed Channels are present around airflow opening when base is curb rest.",
    reference: "Curb Rest Spec 391-200",
    excelRow: 48,
    requiredFacts: ["unit.curbrest"],
    predicate: { "===": [{ var: "unit.curbrest" }, "Yes"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-12",
    semanticKey: "BASE_FORMED_CHANNELS_STACKED",
    scope: "Skid",
    category: "Base",
    order: 12,
    text: "Full height Formed Channels are present around airflow openings when unit is top unit of stacked configuration.",
    reference: "Stacked Unit Framing Detail",
    excelRow: 50,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-13",
    semanticKey: "BASE_AL_DRAIN_SUPPORTS",
    scope: "Skid",
    category: "Base",
    order: 13,
    text: "Aluminum floor drain supports are 5.00\" apart, 2.50\" from center of drain in both directions.",
    reference: "Aluminum Base Standard",
    excelRow: 51,
    requiredFacts: ["unit.floorMaterial"],
    predicate: { "includes": [{ var: "unit.floorMaterial" }, "AL"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-14",
    semanticKey: "BASE_FORMED_CHANNELS_MAX_LEN",
    scope: "Skid",
    category: "Base",
    order: 14,
    text: "Formed Channels do not exceed 144\" in length.",
    reference: "Brake Press Forming Limits",
    excelRow: 52,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-15",
    semanticKey: "BASE_DRAIN_PAN_DOA_SUPPORTS",
    scope: "Skid",
    category: "Base",
    order: 15,
    text: "Drain Pan openings wider than 36\" in DOA, have proper curb angle supports.",
    reference: "DOA Drain Pan Standard",
    excelRow: 53,
    requiredFacts: ["skid.hasDrainPan"],
    predicate: { "===": [{ var: "skid.hasDrainPan" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-16",
    semanticKey: "BASE_NOTES_DIMS_STAMPS",
    scope: "Skid",
    category: "Base",
    order: 16,
    text: "All required dimensions and notes are added (Z-bar dims, Drainpan dims, Construction details, Stamps).",
    reference: "Drafting Standard D-101",
    excelRow: 55,
    requiredFacts: [],
    allowNA: false,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-17",
    semanticKey: "BASE_DRAIN_PAN_ASSY_NUM",
    scope: "Skid",
    category: "Base",
    order: 17,
    text: "Drainpans have the correct assembly number in the respective opening.",
    reference: "Master Assembly Schedule",
    excelRow: 56,
    requiredFacts: ["skid.hasDrainPan"],
    predicate: { "===": [{ var: "skid.hasDrainPan" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-18",
    semanticKey: "BASE_OPENING_ASSY_TYPES",
    scope: "Skid",
    category: "Base",
    order: 18,
    text: "Opening assembly types are correct and have the correct assembly number on the drawing.",
    reference: "Opening Schedule Spec",
    excelRow: 57,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-19",
    semanticKey: "BASE_DRAIN_PAN_BULKHEAD_LOCATING_DIM",
    scope: "Skid",
    category: "Base",
    order: 19,
    text: "Critical locating dim added for Drain pans with bulkheads.",
    reference: "Bulkhead Interface Detail",
    excelRow: 58,
    requiredFacts: ["skid.hasDrainPan"],
    predicate: { "===": [{ var: "skid.hasDrainPan" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "BASE-20",
    semanticKey: "BASE_SUBFLOOR_DRAIN_PAN_GT_45",
    scope: "Skid",
    category: "Base",
    order: 20,
    text: "Subfloors under drain pan openings greater than 45\" are not oversized.",
    reference: "Subfloor Sizing Spec",
    excelRow: 109,
    requiredFacts: ["skid.hasDrainPan"],
    predicate: { "===": [{ var: "skid.hasDrainPan" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  // Archived Base Rules
  {
    id: "BASE-ARC-01",
    semanticKey: "BASE_SUBFLOOR_PULLBACK_ARCHIVE",
    scope: "Skid",
    category: "Base",
    order: 21,
    text: "Subfloors are pulled back 0.25\" from full height formed channels like they are from structural channels.",
    reference: "Subfloor Assembly Detail",
    excelRow: 110,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox",
    isArchived: true
  },
  {
    id: "BASE-ARC-02",
    semanticKey: "BASE_STRUCTURAL_ANGLES_MOM_ARCHIVE",
    scope: "Skid",
    category: "Base",
    order: 22,
    text: "Structural Steel Angles are building in MOM. Base Height should be set to 6 to get them to upload.",
    reference: "MOM Upload Standard",
    excelRow: 117,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox",
    isArchived: true
  },
  {
    id: "BASE-ARC-03",
    semanticKey: "BASE_AL_DRAIN_SUPPORTS_ARCHIVE",
    scope: "Skid",
    category: "Base",
    order: 23,
    text: "Aluminum floor drain supports should be 5.00\" apart, 2.50\" from center of drain in both directions.",
    reference: "Aluminum Base Standard",
    excelRow: 118,
    requiredFacts: ["unit.floorMaterial"],
    allowNA: true,
    verificationMode: "ManualCheckbox",
    isArchived: true
  },

  // =========================================================================
  // 2. HOUSING (Scope: Skid & Unit, No Subgroups)
  // =========================================================================
  {
    id: "HOUS-01",
    semanticKey: "HOUSING_WALL_MAX_SIZE",
    scope: "Skid",
    category: "Housing",
    order: 1,
    text: "Material size does NOT exceed 144\" x 48\".",
    reference: "Casing Sheet Standard",
    excelRow: 61,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-02",
    semanticKey: "HOUSING_CHANNEL_SPACING",
    scope: "Skid",
    category: "Housing",
    order: 2,
    text: "Channel spacing is no less than 3\" from web to web.",
    reference: "Structural Stiffener Spacing",
    excelRow: 62,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-03",
    semanticKey: "HOUSING_HOLE_PATTERN",
    scope: "Skid",
    category: "Housing",
    order: 3,
    text: "The correct hole pattern is used when moving skins, liners, and/or adding channels.",
    reference: "Tooling Hole Pattern Std",
    excelRow: 63,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-04",
    semanticKey: "HOUSING_ROOF_SEALOFF_GAUGE",
    scope: "Unit",
    category: "Housing",
    order: 4,
    text: "Roof seal off angles have the correct material type and material gauge.",
    reference: "Roof Sealing Spec",
    excelRow: 64,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-05",
    semanticKey: "HOUSING_CORRIDOR_SEALOFF_GAUGE",
    scope: "Unit",
    category: "Housing",
    order: 5,
    text: "Corridor wall seal off angles have the correct material type and material gauge.",
    reference: "Vestibule Construction Spec",
    excelRow: 65,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-06",
    semanticKey: "HOUSING_COIL_OPENING_WIDTH_MATCH",
    scope: "Skid",
    category: "Housing",
    order: 6,
    text: "Coil panel openings match the width parameter of the associated coil panel.",
    reference: "Coil Panel Casing Schedule",
    excelRow: 67,
    requiredFacts: ["skid.hasCoils"],
    predicate: { "===": [{ var: "skid.hasCoils" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-07",
    semanticKey: "HOUSING_OUTDOOR_SKIN_HOLES_REMOVED",
    scope: "Unit",
    category: "Housing",
    order: 7,
    text: "Outdoor units have skin holes removed at the unit split.",
    reference: "Weatherproofing Std W-102",
    excelRow: 68,
    requiredFacts: ["unit.unitType"],
    predicate: { "===": [{ var: "unit.unitType" }, "Outdoor"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-08",
    semanticKey: "HOUSING_DOOR_OPENING_SIZES_MATCH",
    scope: "Skid",
    category: "Housing",
    order: 8,
    text: "Door opening sizes match the BOM and Unit Editor.",
    reference: "Access Door Schedule",
    excelRow: 69,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-09",
    semanticKey: "HOUSING_WALL_PANEL_MAX_106",
    scope: "Skid",
    category: "Housing",
    order: 9,
    text: "Wall panels do not exceed 106\" in more than one direction.",
    reference: "Fabrication Machine Limits",
    excelRow: 70,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-10",
    semanticKey: "HOUSING_WALL_HEIGHT_MATCH_UE",
    scope: "Skid",
    category: "Housing",
    order: 10,
    text: "Wall panels match height in the UE.",
    reference: "Unit Dimension Schedule",
    excelRow: 71,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-11",
    semanticKey: "HOUSING_NO_HOLES_WITHOUT_CHANNEL_SUPPORT",
    scope: "Skid",
    category: "Housing",
    order: 11,
    text: "There are no holes in the skins or liners that do not have channel support behind them.",
    reference: "Structural Fastening Std",
    excelRow: 72,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-12",
    semanticKey: "HOUSING_CHANNEL_START_STOP_WALLS",
    scope: "Skid",
    category: "Housing",
    order: 12,
    text: "Channel dimensions start and stop at each wall section.",
    reference: "Framing Detailing Rules",
    excelRow: 73,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-13",
    semanticKey: "HOUSING_SKIN_LINER_MATERIALS_MATCH",
    scope: "Unit",
    category: "Housing",
    order: 13,
    text: "Skin and liner materials match the UE.",
    reference: "Engineering Casing Spec",
    excelRow: 74,
    requiredFacts: ["unit.skinMaterial", "unit.linerMaterial"],
    allowNA: false,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-14",
    semanticKey: "HOUSING_INSULATION_TYPE_CORRECT",
    scope: "Unit",
    category: "Housing",
    order: 14,
    text: "Insulation types are correct.",
    reference: "Thermal Casing Standard",
    excelRow: 75,
    requiredFacts: [],
    allowNA: false,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-15",
    semanticKey: "HOUSING_SPLITS_LOCATED_PROPERLY",
    scope: "Unit",
    category: "Housing",
    order: 15,
    text: "Construction splits and units splits are located where necessary.",
    reference: "Shipping Boundary Plan",
    excelRow: 76,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-16",
    semanticKey: "HOUSING_CORRIDOR_SKIN_OVERLAP",
    scope: "Unit",
    category: "Housing",
    order: 16,
    text: "Skin overlap added for skins on east/west walls on corridor units. Skin overlaps from Vestibules onto Air Tunnel.",
    reference: "Corridor Weatherproofing Spec",
    excelRow: 77,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-17",
    semanticKey: "HOUSING_BULKHEAD_SUPPORT_PRESENT",
    scope: "Skid",
    category: "Housing",
    order: 17,
    text: "Housing support is present for all bulkheads.",
    reference: "Bulkhead Attachment Std",
    excelRow: 78,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-18",
    semanticKey: "HOUSING_ROOF_PANEL_MAX_106",
    scope: "Unit",
    category: "Housing",
    order: 18,
    text: "Roof panels do not exceed 106\" in more than one direction.",
    reference: "Roof Fabrication Limits",
    excelRow: 84,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-19",
    semanticKey: "HOUSING_FILTER_STIFFENERS_ROOF_SUPPORT",
    scope: "Skid",
    category: "Housing",
    order: 19,
    text: "Filter Stiffeners have roof channel support.",
    reference: "Filter Framing Spec",
    excelRow: 90,
    requiredFacts: ["skid.hasFilters"],
    predicate: { "===": [{ var: "skid.hasFilters" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-20",
    semanticKey: "HOUSING_SPECIAL_ROOF_CAPS",
    scope: "Unit",
    category: "Housing",
    order: 20,
    text: "Special Roof Caps for Non-Rectangular, Pipe Chases, and Tiered units have been adjusted to work with special housing.",
    reference: "Special Housing Standards",
    excelRow: 92,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-21",
    semanticKey: "HOUSING_OUTDOOR_GALV_ROOF_SKIN",
    scope: "Unit",
    category: "Housing",
    order: 21,
    text: "Outdoor units have galvanized roof skins. (Edit Manual - Unit_Construction_Rules, page 23)",
    reference: "Unit Construction Rules p.23",
    excelRow: 93,
    requiredFacts: ["unit.unitType"],
    predicate: { "===": [{ var: "unit.unitType" }, "Outdoor"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-22",
    semanticKey: "HOUSING_ROOF_OPENING_SHIPPING_COVERS",
    scope: "Unit",
    category: "Housing",
    order: 22,
    text: "Roof openings without dampers have shipping covers present in the MOM BOM.",
    reference: "Shipping Protection Spec",
    excelRow: 94,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-23",
    semanticKey: "HOUSING_TIERING_ANGLES_GAUGE",
    scope: "Unit",
    category: "Housing",
    order: 23,
    text: "Tiering angles are the correct gauge and material.",
    reference: "Tiering Attachment Standard",
    excelRow: 145,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-24",
    semanticKey: "HOUSING_ALUMINUM_CORNER_LINERS_14GA",
    scope: "Unit",
    category: "Housing",
    order: 24,
    text: "Aluminum corner liners are 14ga (.080\").",
    reference: "Casing Corner Liners Spec",
    excelRow: 146,
    requiredFacts: ["unit.linerMaterial"],
    predicate: { "includes": [{ var: "unit.linerMaterial" }, "AL"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "HOUS-25",
    semanticKey: "HOUSING_THERMAL_BREAK_SETTING",
    scope: "Unit",
    category: "Housing",
    order: 25,
    text: "Panels for thermal break units have Thermal Break parameter set to Yes in CAD models.",
    reference: "Housing Design Standard H-201",
    excelRow: 204,
    requiredFacts: ["unit.thermalBreak"],
    predicate: { "===": [{ var: "unit.thermalBreak" }, "Yes"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },

  // =========================================================================
  // 3. KNOCKDOWN (Scope: Unit, No Subgroups)
  // =========================================================================
  {
    id: "KNOCK-01",
    semanticKey: "KNOCKDOWN_RECONNECTS_SUBASSEMBLY",
    scope: "Unit",
    category: "Knockdown",
    order: 1,
    text: "Reconnects are broken into sub-assemblies small enough for knockdown requirement after welding.",
    reference: "Knockdown Assembly Guide",
    excelRow: 193,
    requiredFacts: ["unit.knockdown"],
    predicate: { "===": [{ var: "unit.knockdown" }, "Yes"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "KNOCK-02",
    semanticKey: "KNOCKDOWN_WELDED_STANDS_FIT",
    scope: "Unit",
    category: "Knockdown",
    order: 2,
    text: "Structural Stands that are welded are designed to fit through Knockdown opening.",
    reference: "Knockdown Envelope Limits",
    excelRow: 194,
    requiredFacts: ["unit.knockdown"],
    predicate: { "===": [{ var: "unit.knockdown" }, "Yes"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "KNOCK-03",
    semanticKey: "KNOCKDOWN_COMPONENT_OPENING_FIT",
    scope: "Unit",
    category: "Knockdown",
    order: 3,
    text: "All components are measured against the knockdown opening size (Height x Width) and by depth. If depth is not specified, check with PE.",
    reference: "Knockdown Clearance Spec",
    excelRow: 195,
    requiredFacts: ["unit.knockdown"],
    predicate: { "===": [{ var: "unit.knockdown" }, "Yes"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "KNOCK-04",
    semanticKey: "KNOCKDOWN_HOUSING_SPLITS_EVEN",
    scope: "Unit",
    category: "Knockdown",
    order: 4,
    text: "Housing Splits added to meet knockdown requirements and are added in a way to split walls as evenly as possible.",
    reference: "Knockdown Wall Splitting Rule",
    excelRow: 196,
    requiredFacts: ["unit.knockdown"],
    predicate: { "===": [{ var: "unit.knockdown" }, "Yes"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },

  // =========================================================================
  // 4. UTL (Scope: Unit & Skid, No Subgroups)
  // =========================================================================
  {
    id: "UTL-01",
    semanticKey: "UTL_DRAIN_PAN_ANGLE_SKIN_COVERAGE",
    scope: "Skid",
    category: "UTL",
    order: 1,
    text: "Drain Pan - UTL formed angle supports under the Left and Right flanges of the drainpan have skin coverage.",
    reference: "UTL Drain Pan Detail",
    excelRow: 183,
    requiredFacts: ["unit.utl"],
    predicate: { "includes": [{ var: "unit.utl" }, "Yes"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "UTL-02",
    semanticKey: "UTL_WALL_PANELS_HEIGHT_REDUCTION",
    scope: "Unit",
    category: "UTL",
    order: 2,
    text: "Wall panels are reduced in height for UTL construction.",
    reference: "UTL Wall Panel Sizing Spec",
    excelRow: 185,
    requiredFacts: ["unit.utl"],
    predicate: { "includes": [{ var: "unit.utl" }, "Yes"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "UTL-03",
    semanticKey: "UTL_PERIMETER_ANGLE_SPLIT_NOTCH",
    scope: "Unit",
    category: "UTL",
    order: 3,
    text: "Perimeter angles with upturned lips are notched at unit splits for reconnects: 1.56\" notch for Baseline; 2.06\" notch for Seismic.",
    reference: "UTL Detail Standard 391-30002",
    excelRow: 186,
    requiredFacts: ["unit.utl", "unit.isSeismic"],
    predicate: { "includes": [{ var: "unit.utl" }, "Yes"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "UTL-04",
    semanticKey: "UTL_HEADER_PANEL_Y_OFFSET",
    scope: "Unit",
    category: "UTL",
    order: 4,
    text: "Header panels for units with UTL have Y offset in the coil panel parameters equal to UTL height, unless panel is on a footer, then set to zero.",
    reference: "UTL Coil Panel Guide",
    excelRow: 187,
    requiredFacts: ["unit.utl"],
    predicate: { "includes": [{ var: "unit.utl" }, "Yes"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "UTL-05",
    semanticKey: "UTL_VESTIBULE_NO_UTL_RULE",
    scope: "Unit",
    category: "UTL",
    order: 5,
    text: "Upturned Lips are not present in the Vestibule unless SQ'ed.",
    reference: "Vestibule Standard Spec",
    excelRow: 189,
    requiredFacts: ["unit.utl"],
    predicate: { "includes": [{ var: "unit.utl" }, "Yes"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "UTL-06",
    semanticKey: "UTL_SHARED_WALL_FOOTERS",
    scope: "Unit",
    category: "UTL",
    order: 6,
    text: "Coil Panels - Footers for coil panels in shared walls are present, and equal to UTL height, when both tunnels of the shared wall are upturned lip.",
    reference: "Shared Wall Coil Detail",
    excelRow: 190,
    requiredFacts: ["unit.utl"],
    predicate: { "includes": [{ var: "unit.utl" }, "Yes"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "UTL-07",
    semanticKey: "UTL_HEADER_PANELS_ON_FOOTERS_HEIGHT",
    scope: "Unit",
    category: "UTL",
    order: 7,
    text: "Header panels that are on footers have their height reduced by the footer height.",
    reference: "Footer Coil Panel Specification",
    excelRow: 191,
    requiredFacts: ["unit.utl"],
    predicate: { "includes": [{ var: "unit.utl" }, "Yes"] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },

  // =========================================================================
  // 5. PAPERWORK (Scope: Unit, No Subgroups)
  // =========================================================================
  {
    id: "PAPER-01",
    semanticKey: "PAPERWORK_BASERAIL_DRAIN_PAN_LOCATING_DIM",
    scope: "Unit",
    category: "Paperwork",
    order: 1,
    text: "Critical locating dim added for Drain pans with bulkheads.",
    reference: "Paperwork Release Standard",
    excelRow: 149,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "PAPER-02",
    semanticKey: "PAPERWORK_BASERAIL_BOM_MATERIAL_GAUGE",
    scope: "Unit",
    category: "Paperwork",
    order: 2,
    text: "Correct material type and material gauge are present in baserail paperwork BOMs.",
    reference: "Release Packet Verification",
    excelRow: 150,
    requiredFacts: [],
    allowNA: false,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "PAPER-03",
    semanticKey: "PAPERWORK_BASERAIL_DRAIN_PAN_ASSY_NUM",
    scope: "Unit",
    category: "Paperwork",
    order: 3,
    text: "Drainpans have the correct assembly number in the respective opening in baserail paperwork.",
    reference: "Baserail Packet Assembly Table",
    excelRow: 151,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "PAPER-04",
    semanticKey: "PAPERWORK_BASERAIL_REQUIRED_DIMS_NOTES",
    scope: "Unit",
    category: "Paperwork",
    order: 4,
    text: "Required dimensions and notes including ID of z-bars, drain hole location, drainpan location dim, etc. have been added to baserail drawings.",
    reference: "Drafting Checklist",
    excelRow: 152,
    requiredFacts: [],
    allowNA: false,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "PAPER-05",
    semanticKey: "PAPERWORK_BASERAIL_PART_NUMBERS",
    scope: "Unit",
    category: "Paperwork",
    order: 5,
    text: "Added library parts and changed parts have a part number on the baserail paperwork.",
    reference: "Baserail Packet Guide",
    excelRow: 153,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "PAPER-06",
    semanticKey: "PAPERWORK_WALL_BOM_MATERIAL_GAUGE",
    scope: "Unit",
    category: "Paperwork",
    order: 6,
    text: "Correct material type and material gauge are present in wall paperwork BOMs.",
    reference: "Wall Packet Verification",
    excelRow: 155,
    requiredFacts: [],
    allowNA: false,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "PAPER-07",
    semanticKey: "PAPERWORK_WALL_INSULATION_CORRECT",
    scope: "Unit",
    category: "Paperwork",
    order: 7,
    text: "Insulation types are correct in wall paperwork.",
    reference: "Wall Insulation Spec",
    excelRow: 156,
    requiredFacts: [],
    allowNA: false,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "PAPER-08",
    semanticKey: "PAPERWORK_WALL_PART_NUMBERS",
    scope: "Unit",
    category: "Paperwork",
    order: 8,
    text: "All added library parts and changed parts have a part number on the wall paperwork.",
    reference: "Wall Packet Guide",
    excelRow: 157,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "PAPER-09",
    semanticKey: "PAPERWORK_SKID_BOM_MATERIAL_GAUGE",
    scope: "Unit",
    category: "Paperwork",
    order: 9,
    text: "Correct material type and material gauge are present in skid paperwork BOMs.",
    reference: "Skid Packet Verification",
    excelRow: 159,
    requiredFacts: [],
    allowNA: false,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "PAPER-10",
    semanticKey: "PAPERWORK_SKID_BULKHEADS_DIMENSIONED",
    scope: "Unit",
    category: "Paperwork",
    order: 10,
    text: "All bulkheads are present and dimensioned correctly on the skid paperwork.",
    reference: "Bulkhead Dimensioning Check",
    excelRow: 160,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "PAPER-11",
    semanticKey: "PAPERWORK_SKID_INTERNALS_ASSY_NUM",
    scope: "Unit",
    category: "Paperwork",
    order: 11,
    text: "All internals have the correct assembly number in the skid BOM.",
    reference: "Internal Assembly Schedule",
    excelRow: 161,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "PAPER-12",
    semanticKey: "PAPERWORK_SKID_PART_NUMBERS",
    scope: "Unit",
    category: "Paperwork",
    order: 12,
    text: "All added library parts and changed parts have a part number on the skid paperwork.",
    reference: "Skid Packet Guide",
    excelRow: 162,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },

  // =========================================================================
  // 6. MOM (Scope: Unit, No Subgroups)
  // =========================================================================
  {
    id: "MOM-01",
    semanticKey: "MOM_DETAILER_DOC_UPLOADED",
    scope: "Unit",
    category: "MOM",
    order: 1,
    text: "The detailer information document is uploaded to the CAD/MAPICS document section.",
    reference: "Detailing Release Checklist",
    excelRow: 164,
    requiredFacts: [],
    allowNA: false,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "MOM-02",
    semanticKey: "MOM_MAPICS_BOM_CLEAN",
    scope: "Unit",
    category: "MOM",
    order: 2,
    text: "The MAPICS BOM is uploaded and clean.",
    reference: "MAPICS Process Guide",
    excelRow: 165,
    requiredFacts: [],
    allowNA: false,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "MOM-03",
    semanticKey: "MOM_SHELL_GENERATION_SETTING",
    scope: "Unit",
    category: "MOM",
    order: 3,
    text: "Unit Editor shell options are set to the correct shell generation.",
    reference: "MOM Configuration Guide",
    excelRow: 166,
    requiredFacts: [],
    allowNA: false,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "MOM-04",
    semanticKey: "ISG_PART_SELECT_RUN",
    scope: "Unit",
    category: "MOM",
    order: 4,
    text: "Post ISG part select has been ran, unnecessary parts have been removed, and all parts are built and in MAPICS.",
    reference: "ISG Automation Guide",
    excelRow: 168,
    requiredFacts: [],
    allowNA: false,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "MOM-05",
    semanticKey: "ISG_SURFACE_SUMMARY_NO_DUPLICATES",
    scope: "Unit",
    category: "MOM",
    order: 5,
    text: "Surface Summary Generation has been ran and there are no duplicate surfaces in the BOM.",
    reference: "Surface Summary Process",
    excelRow: 169,
    requiredFacts: [],
    allowNA: false,
    verificationMode: "ManualCheckbox"
  },

  // =========================================================================
  // 7. INTERNALS (Scope: Skid & Segment, Has Subgroups)
  // =========================================================================
  // Subgroup: Fan Segments
  {
    id: "INT-FAN-01",
    semanticKey: "FAN_MANUAL_DRIVE_KITS",
    scope: "Skid",
    category: "Internals",
    subgroup: "Fan Segments",
    order: 1,
    text: "Drive kits for belt driven fans that MOM did not part select, have been created and added to the BOM using the Manual Drive Kit process.",
    reference: "Fan Drive Kit Standard",
    excelRow: 175,
    requiredFacts: ["skid.hasFans"],
    predicate: { "===": [{ var: "skid.hasFans" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-FAN-02",
    semanticKey: "FAN_SQ_MODELS_DRAWINGS_DIMS",
    scope: "Skid",
    category: "Internals",
    subgroup: "Fan Segments",
    order: 2,
    text: "SQ'ed fan models have correct drawings, bend indicators, dimensions, part quantity, and material.",
    reference: "Fan SQ Standard",
    excelRow: 176,
    requiredFacts: ["skid.hasFans"],
    predicate: { "===": [{ var: "skid.hasFans" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-FAN-03",
    semanticKey: "FAN_NEW_SQ_PARAMETERS_FEATURES",
    scope: "Skid",
    category: "Internals",
    subgroup: "Fan Segments",
    order: 3,
    text: "New/SQ fan models have the correct parameters/features used per component specifications.",
    reference: "Component Specification Manual",
    excelRow: 177,
    requiredFacts: ["skid.hasFans"],
    predicate: { "===": [{ var: "skid.hasFans" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },

  // Subgroup: Filter Segments
  {
    id: "INT-FILT-01",
    semanticKey: "INTERNAL_FILTER_DOOR_CLEARANCE",
    scope: "Skid",
    category: "Internals",
    subgroup: "Filter Segments",
    order: 1,
    text: "Slide-in (side-load) filters have enough door clearance.",
    reference: "Service Clearance Guidelines p.14",
    excelRow: 181,
    requiredFacts: ["skid.hasFilters"],
    predicate: { "===": [{ var: "skid.hasFilters" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },

  // Subgroup: Access Segments (Bulkheads & General Internals)
  {
    id: "INT-ACC-01",
    semanticKey: "INTERNAL_BULKHEAD_MATERIAL_MATCH",
    scope: "Skid",
    category: "Internals",
    subgroup: "Access Segments",
    order: 1,
    text: "Bulkhead materials match the UE/Spec Sheet.",
    reference: "Bulkhead Material Spec",
    excelRow: 178,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-ACC-02",
    semanticKey: "INTERNAL_SQ_DEVIATIONS_MATCH",
    scope: "Skid",
    category: "Internals",
    subgroup: "Access Segments",
    order: 2,
    text: "Internals have been changed to match SQs/Deviations.",
    reference: "Order Release SQ Summary",
    excelRow: 179,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-ACC-03",
    semanticKey: "INTERNAL_IEC_NON_SQ_ASSEMBLIES_CLEANUP",
    scope: "Skid",
    category: "Internals",
    subgroup: "Access Segments",
    order: 3,
    text: "All non-SQ-ed assemblies left by IEC have been deleted from the BOM after surface generation.",
    reference: "BOM Cleanup Standard",
    excelRow: 180,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },

  // Subgroup: Coil Segments (Coil Panels + Drain Pans)
  {
    id: "INT-COIL-01",
    semanticKey: "COIL_PANEL_WALL_OPENING_MATCH",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 1,
    text: "Wall openings and coil panel width parameter match.",
    reference: "Coil Opening Parameter Check",
    excelRow: 199,
    requiredFacts: ["skid.hasCoils"],
    predicate: { "===": [{ var: "skid.hasCoils" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-COIL-02",
    semanticKey: "COIL_PANEL_HELD_NO_BOM_ASSEMBLY",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 2,
    text: "Held Coil panels have no assembly in the MOM BOM.",
    reference: "Held Coil BOM Procedure",
    excelRow: 200,
    requiredFacts: ["skid.hasCoils"],
    predicate: { "===": [{ var: "skid.hasCoils" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-COIL-03",
    semanticKey: "COIL_PANEL_AIRFLOW_DIRECTION",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 3,
    text: "Coil Panels have the correct airflow direction.",
    reference: "Piping & Airflow Schedule",
    excelRow: 201,
    requiredFacts: ["skid.hasCoils"],
    predicate: { "===": [{ var: "skid.hasCoils" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-COIL-04",
    semanticKey: "COIL_PANEL_STAGGERED_VENT_DRAIN_OFF",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 4,
    text: "The Downstream staggered coil header panels have the vent and drain parameter turned off unless an SQ requires extended vent and drains.",
    reference: "Staggered Coil Spec",
    excelRow: 203,
    requiredFacts: ["skid.hasCoils"],
    predicate: { "===": [{ var: "skid.hasCoils" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-COIL-05",
    semanticKey: "COIL_PANEL_HELD_MARKED_ON_PACKET",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 5,
    text: "Held Coil Panels are marked as such on the Int-Ext/Skid Packet.",
    reference: "Skid Packet Drafting Standard",
    excelRow: 205,
    requiredFacts: ["skid.hasCoils"],
    predicate: { "===": [{ var: "skid.hasCoils" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-COIL-06",
    semanticKey: "COIL_PANEL_BOM_BALLOONS_PRESENT",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 6,
    text: "Coil panels have BOM line items and balloons on the Skid Packet.",
    reference: "Drafting Balloon Rules",
    excelRow: 206,
    requiredFacts: ["skid.hasCoils"],
    predicate: { "===": [{ var: "skid.hasCoils" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  // Drain Pan rules inside Coil Segments
  {
    id: "INT-DPAN-01",
    semanticKey: "DPAN_BASE_OPENING_FIT",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 7,
    text: "Drain pan fits in length of base opening.",
    reference: "Drain Pan Layout Standard",
    excelRow: 214,
    requiredFacts: ["skid.hasDrainPan"],
    predicate: { "===": [{ var: "skid.hasDrainPan" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-DPAN-02",
    semanticKey: "DPAN_SQ_SUPPORTS_RISERS_QTY",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 8,
    text: "Drain pan has correct qty and location of supports and risers for SQ'ed drain pans.",
    reference: "Engineering Coil Pan Standard",
    excelRow: 215,
    requiredFacts: ["skid.hasDrainPan"],
    predicate: { "===": [{ var: "skid.hasDrainPan" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-DPAN-03",
    semanticKey: "DPAN_SUPPORTS_RISERS_MATCH_BOM",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 9,
    text: "Qty of supports and risers match the BOM.",
    reference: "BOM Verification Procedure",
    excelRow: 216,
    requiredFacts: ["skid.hasDrainPan"],
    predicate: { "===": [{ var: "skid.hasDrainPan" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-DPAN-04",
    semanticKey: "DPAN_LADDER_RACK_HOLES",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 10,
    text: "Holes in ladder rack for each coil support.",
    reference: "Ladder Rack Standard",
    excelRow: 217,
    requiredFacts: ["skid.hasDrainPan"],
    predicate: { "===": [{ var: "skid.hasDrainPan" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-DPAN-05",
    semanticKey: "DPAN_HANDING_CORRECT",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 11,
    text: "Drain pan has correct handing per the UE.",
    reference: "Submittal Schedule",
    excelRow: 218,
    requiredFacts: ["skid.hasDrainPan"],
    predicate: { "===": [{ var: "skid.hasDrainPan" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-DPAN-06",
    semanticKey: "DPAN_WIDTH_REDUCED_1_25",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 12,
    text: "Drain pan to be reduced 1.25\" from Left and Right support channels.",
    reference: "Pan Channel Clearance Rule",
    excelRow: 219,
    requiredFacts: ["skid.hasDrainPan"],
    predicate: { "===": [{ var: "skid.hasDrainPan" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-DPAN-07",
    semanticKey: "DPAN_3PIECE_SLOPE_CORRECT",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 13,
    text: "3 piece drain pan all slope properly.",
    reference: "ASHRAE 62.1 Drainage Standard",
    excelRow: 220,
    requiredFacts: ["skid.hasDrainPan"],
    predicate: { "===": [{ var: "skid.hasDrainPan" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-DPAN-08",
    semanticKey: "DPAN_BASE_OPENINGS_MATCH_UE",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 14,
    text: "Drain pan openings in base surfaces match opening dimensions and location in UE.",
    reference: "Unit Editor Base Map",
    excelRow: 221,
    requiredFacts: ["skid.hasDrainPan"],
    predicate: { "===": [{ var: "skid.hasDrainPan" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-DPAN-09",
    semanticKey: "DPAN_FLANGES_FIT_PERIMETER_ANGLES",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 15,
    text: "Drain pan flanges fit between perimeter angles.",
    reference: "Base Clearance Specification",
    excelRow: 222,
    requiredFacts: ["skid.hasDrainPan"],
    predicate: { "===": [{ var: "skid.hasDrainPan" }, true] },
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  // Archived Coil Segment Rules
  {
    id: "INT-COIL-ARC-01",
    semanticKey: "COIL_PANEL_RETURN_VENT_DRAIN_OFF_ARCHIVE",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 16,
    text: "Return panels have the vent and drain parameter turned off.",
    reference: "Return Coil Parameter Spec",
    excelRow: 202,
    requiredFacts: ["skid.hasCoils"],
    allowNA: true,
    verificationMode: "ManualCheckbox",
    isArchived: true
  },
  {
    id: "INT-DPAN-ARC-01",
    semanticKey: "DPAN_MASTER_MODEL_391_10006_021_ARCHIVE",
    scope: "Skid",
    category: "Internals",
    subgroup: "Coil Segments",
    order: 17,
    text: "Drain pan is using MM# 391-10006-021.",
    reference: "Master Model Catalog",
    excelRow: 223,
    requiredFacts: ["skid.hasDrainPan"],
    allowNA: true,
    verificationMode: "ManualCheckbox",
    isArchived: true
  },

  // Subgroup: Reconnects (under Internals)
  {
    id: "INT-RECON-01",
    semanticKey: "RECONNECT_TYPE_CORRECT",
    scope: "Unit",
    category: "Internals",
    subgroup: "Reconnects",
    order: 1,
    text: "Reconnects are the correct type for its use in the unit.",
    reference: "Split Reconnect Schedule",
    excelRow: 209,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-RECON-02",
    semanticKey: "RECONNECT_LINER_MATERIAL_MATCH",
    scope: "Unit",
    category: "Internals",
    subgroup: "Reconnects",
    order: 2,
    text: "All Reconnects match the liner material of the segment they are in. Aluminum liner sections should have Stainless Reconnects.",
    reference: "Materials Specification Sec 2",
    excelRow: 210,
    requiredFacts: ["unit.linerMaterial"],
    allowNA: false,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-RECON-03",
    semanticKey: "RECONNECT_QUANTITY_PER_SPLIT",
    scope: "Unit",
    category: "Internals",
    subgroup: "Reconnects",
    order: 3,
    text: "Each Split has the correct quantity of reconnects.",
    reference: "Split Connection Table",
    excelRow: 211,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  },
  {
    id: "INT-RECON-04",
    semanticKey: "RECONNECT_IW_IH_TUNNEL_FIT",
    scope: "Unit",
    category: "Internals",
    subgroup: "Reconnects",
    order: 4,
    text: "Reconnects have the correct IW and IH for the tunnel they are in. IW parameter should be reduced 0.50\" from tunnel IW.",
    reference: "Reconnect Sizing Rule",
    excelRow: 212,
    requiredFacts: [],
    allowNA: true,
    verificationMode: "ManualCheckbox"
  }
];

const templateMap = {
  templateVersion: "14.0.0",
  sheetNames: {
    revisionList: "Revision List",
    verificationList: "Verification List",
    checkInformation: "Check Information",
    comments: "Comments",
    base: "Base",
    drainPan: "Drain Pan",
    housing: "Housing",
    paperwork: "Paperwork",
    internal: "Internal",
    coilPanels: "Coil Panels",
    reconnects: "Reconnects",
    mom: "MOM"
  },
  categories: [
    { key: "Base", hasSubgroups: false },
    { key: "Housing", hasSubgroups: false },
    { key: "Knockdown", hasSubgroups: false },
    { key: "UTL", hasSubgroups: false },
    { key: "Paperwork", hasSubgroups: false },
    { key: "MOM", hasSubgroups: false },
    { key: "Internals", hasSubgroups: true, subgroups: ["Fan Segments", "Coil Segments", "Access Segments", "Filter Segments", "Reconnects"] }
  ],
  generalFields: {
    "unit.detailer": { sheet: "Verification List", cell: "D3" },
    "unit.date": { sheet: "Verification List", cell: "D4" },
    "unit.jobName": { sheet: "Verification List", cell: "D5" },
    "unit.comNumber": { sheet: "Verification List", cell: "D6" },
    "unit.shellType": { sheet: "Verification List", cell: "D7" },
    "unit.unitType": { sheet: "Verification List", cell: "D8" },
    "unit.baseHeight": { sheet: "Verification List", cell: "D9" },
    "unit.wallThickness": { sheet: "Verification List", cell: "D10" },
    "unit.thermalBreak": { sheet: "Verification List", cell: "D11" },
    "unit.roofPeak": { sheet: "Verification List", cell: "D12" },
    "unit.curbrest": { sheet: "Verification List", cell: "D13" },
    "unit.noa": { sheet: "Verification List", cell: "D14" },
    "unit.isSeismic": { sheet: "Verification List", cell: "D15" },
    "unit.location": { sheet: "Verification List", cell: "D16" },
    "unit.knockdown": { sheet: "Verification List", cell: "D17" },
    "unit.utl": { sheet: "Verification List", cell: "D18" },
    "unit.linerMaterial": { sheet: "Verification List", cell: "D19" },
    "unit.linerGauge": { sheet: "Verification List", cell: "F19" },
    "unit.skinMaterial": { sheet: "Verification List", cell: "D20" },
    "unit.skinGauge": { sheet: "Verification List", cell: "F20" },
    "unit.floorMaterial": { sheet: "Verification List", cell: "D21" },
    "unit.floorGauge": { sheet: "Verification List", cell: "F21" },
    "generalComments": { sheet: "Verification List", cell: "D22" }
  },
  sqRange: {
    sheet: "Verification List",
    startRow: 4,
    endRow: 25,
    slotCol: "G",
    textCol: "H"
  },
  columns: {
    verificationList: {
      ruleNumber: "B",
      ruleText: "C",
      na: "S",
      detailerCheck: "T",
      checkerCheck: "V",
      comments: "Y",
      initials: "Z"
    }
  },
  ruleCellMappings: {}
};

rules.forEach(r => {
  templateMap.ruleCellMappings[r.semanticKey] = {
    ruleId: r.id,
    row: r.excelRow,
    naCell: `S${r.excelRow}`,
    detailerCell: `T${r.excelRow}`,
    checkerCell: `V${r.excelRow}`,
    commentsCell: `Y${r.excelRow}`,
    initialsCell: `Z${r.excelRow}`
  };
});

function sha256(content) {
  return crypto.createHash("sha256").update(content).digest("hex");
}

const rulePackFileOrder = [
  "rules.json",
  "template_map.json",
  "approved_mappings.json",
  "template.xlsx"
];

function computeBundleSha256(files) {
  return sha256(rulePackFileOrder.map(name => `${name}:${files[name].sha256}`).join("\n"));
}

const targetDirs = ["src/rulepack", "resources/rulepack"];

for (const dir of targetDirs) {
  fs.mkdirSync(dir, { recursive: true });

  const rulesJson = JSON.stringify(rules, null, 2);
  const templateMapJson = JSON.stringify(templateMap, null, 2);
  const approvedMappingsJson = JSON.stringify(approvedMappings, null, 2);

  fs.writeFileSync(path.join(dir, "rules.json"), rulesJson, "utf8");
  fs.writeFileSync(path.join(dir, "template_map.json"), templateMapJson, "utf8");
  fs.writeFileSync(path.join(dir, "approved_mappings.json"), approvedMappingsJson, "utf8");

  const templatePath = path.join(dir, "template.xlsx");
  if (!fs.existsSync(templatePath)) {
    throw new Error(`Cannot build rule pack without ${templatePath}`);
  }
  const templateSha = sha256(fs.readFileSync(templatePath));

  const activeCount = rules.filter(r => !r.isArchived).length;
  const archivedCount = rules.filter(r => r.isArchived).length;

  const files = {
    "rules.json": { sha256: sha256(rulesJson), totalRules: rules.length, activeRules: activeCount, archivedRules: archivedCount },
    "template_map.json": { sha256: sha256(templateMapJson) },
    "approved_mappings.json": { sha256: sha256(approvedMappingsJson) },
    "template.xlsx": { sha256: templateSha }
  };

  const manifest = {
    name: "AHU Detailing Verification Rule Pack",
    version: "14.0.0",
    generatedAt: new Date().toISOString(),
    bundleSha256: computeBundleSha256(files),
    files
  };

  fs.writeFileSync(path.join(dir, "manifest.json"), JSON.stringify(manifest, null, 2), "utf8");
  console.log(`Successfully generated rulepack bundle in ${dir} with ${rules.length} rules (${activeCount} active, ${archivedCount} archived).`);
}
